// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Conexión directa (sin pgbouncer) usada solo por el CLI de Prisma
    // (migrate / db pull / studio). El runtime de la app usa DATABASE_URL
    // a través de un driver adapter (ver src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
